# Generated by Django 4.0.7 on 2023-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_whom', models.CharField(max_length=50)),
                ('to_whom', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
